version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: campus_postgres
    restart: always
    environment:
      POSTGRES_USER: campus_user
      POSTGRES_PASSWORD: campus_pass
      POSTGRES_DB: campus_reservation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campus_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
